### ISSUE TITLE
provider identifier should be equal

### ISSUE THREAD

**Issue by marde16** [HCL-TECH-SOFTWARE/hclds-keycloak#2]
In [Configure Keycloak as an OIDC IdP for HCL Connections](https://github.com/HCL-TECH-SOFTWARE/hclds-keycloak/blob/main/docs/integration/ds-integration/cnx-keycloak-configuration.md#configure-keycloak-as-an-oidc-idp-for-hcl-connections) `keycloak` is used as provider.identifier while `hcl` is used in [Configuring the OIDC RP TAI against your IdP](https://github.com/HCL-TECH-SOFTWARE/hclds-keycloak/blob/main/docs/integration/ds-integration/cnx-integration.md#configuring-the-oidc-rp-tai-against-your-idp)

Redirect URI definition in **Configure Keycloak as an OIDC IdP for HCL Connections**
https://github.com/HCL-TECH-SOFTWARE/hclds-keycloak/blob/b6ef56962ab2bfddef405ec0f3faeced28815e06/docs/integration/ds-integration/cnx-keycloak-configuration.md?plain=1#L33

provider.identifier definition in **Configuring the OIDC RP TAI against your IdP**
https://github.com/HCL-TECH-SOFTWARE/hclds-keycloak/blob/b6ef56962ab2bfddef405ec0f3faeced28815e06/docs/integration/ds-integration/cnx-integration.md?plain=1#L74

Both names for the provider identifier have to be equal.

**Comment by caiaga** [comment]
@marde16 Thank you for bringing this up and the raised PR as well. You are right and we will look into adjusting this mismatch. We have some more points raised on the Connections OIDC documentation piece, which we currently review and plan to work back into it.

**Comment by VinayakPatilHcl** [comment]
Corrected provider identifier values as part of https://github.com/HCL-TECH-SOFTWARE/hclds-keycloak/pull/8
