### ISSUE TITLE
missing OIDC troubleshooting document

### ISSUE THREAD

**Issue by marde16** [HCL-TECH-SOFTWARE/hclds-keycloak#7]
In the keycloak project I don't find a troubleshooting document about OIDC and Connections.

This IBM knowledge base document [MustGather: Web Single Sign-on problems with WebSphere Application Server](https://www.ibm.com/support/pages/mustgather-web-single-sign-problems-websphere-application-server) is a good starting point for a troubleshooting document in this project.

For troubleshooting OIDC on WebSphere you can use the debug parameters for **OpenID Connect (OIDC), OpenID 2.0, and JWT authentication**
`*=info:com.ibm.ws.security.oidc.*=all:com.ibm.ws.security.openidconnect.*=all:com.ibm.ws.security.openid20.*=all:com.ibm.ws.security.web.*=all`

**Comment by VinayakPatilHcl** [comment]
Added troubleshoot doc as part of https://github.com/HCL-TECH-SOFTWARE/hclds-keycloak/pull/8
